apiVersion: v1
kind: Service
metadata:
  name: home-system-backend
spec:
  selector:
    product: home-system
    component: backend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
