apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-backend

data:
  jdbc_url: {{ .Values.database.jdbc_url }}
  db_user: {{ .Values.database.db_user }}
  db_pass: {{ .Values.database.db_pass }}