apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-backend

data:
  jdbc_url: {{ .Values.database.jdbc_url | b64enc }}
  db_user: {{ .Values.database.db_user | b64enc }}
  db_pass: {{ .Values.database.db_pass | b64enc }}