name: Connect to wireguard
# Schema: https://json.schemastore.org/github-action.json

defaults:
  run:
    shell: bash

inputs:
  WIREGUARD_CLIENT_PRIVATE_KEY:
    description: 'Private Client Key'
    required: true
  WIREGUARD_CLIENT_IP:
    description: 'IP for the client'
    required: true
  WIREGUARD_ALLOWED_IPS:
    description: 'Allowed IPs'
    required: true
  WIREGUARD_SERVER_PUBLIC_KEY:
    description: 'Public key of the server'
    required: true
  WIREGUARD_ENDPOINT:
    description: 'Endpoint of the server'
    required: true


runs:
  using: composite
  steps:
    - run: sudo apt install wireguard
    - run: echo "${{ inputs.WIREGUARD_CLIENT_PRIVATE_KEY }}" > privatekey
    - run: sudo ip link add dev wg0 type wireguard
    - run: sudo ip address add dev wg0 ${{ inputs.WIREGUARD_CLIENT_IP }} peer ${{ inputs.WIREGUARD_ALLOWED_IPS }}
    - run: sudo wg set wg0 private-key privatekey peer ${{ inputs.WIREGUARD_SERVER_PUBLIC_KEY }} allowed-ips ${{ inputs.WIREGUARD_ALLOWED_IPS }} endpoint ${{ inputs.WIREGUARD_ENDPOINT }}
    - run: sudo ip link set up dev wg0

