apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-telemetry
spec:
  selector:
    product: home-system
    component: telemetry
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
