name: Connect to wireguard
# Schema: https://json.schemastore.org/github-action.json

runs:
  using: 'composite'
  steps:
    - run: sudo apt install wireguard
    - run: echo "${{ secrets.WIREGUARD_CLIENT_PRIVATE_KEY }}" > privatekey
    - run: sudo ip link add dev wg0 type wireguard
    - run: sudo ip address add dev wg0 ${{ secrets.WIREGUARD_CLIENT_IP }} peer ${{ secrets.WIREGUARD_ALLOWED_IPS }}
    - run: sudo wg set wg0 private-key privatekey peer ${{ secrets.WIREGUARD_SERVER_PUBLIC_KEY }} allowed-ips ${{ secrets.WIREGUARD_ALLOWED_IPS }} endpoint ${{ secrets.WIREGUARD_ENDPOINT }}
    - run: sudo ip link set up dev wg0

